#+title: Обучение Python 2023
* Вводное занятие 31 января 2023
1) Программирование - это решение проблем.
2) Программирование и разработка ПО - это разные вещи. Разработка ПО включает в себя программирование.
3) Чем отличает этот "курс" от того, что было у меня до этого? Отличается тем, что я отталкиваюсь и от ваших потребностей.
4) Python
5) Направления использования:
   1) Автоматизация тестирования. Мероприятия по обеспечению качества на ЯП Python.
   2) Разработка бэкендов для веб сайтов.
   3) Machine Learning.
   4) Разработка GUI (настольные приложения) -> PyQT
   5) Обработка и анализ информации. Замена Excel. Pandas, SciPy, NumPy.
6) Требования к слушателям:
   1) 1-2 часа очных занятий (возможно потом перейдем частично в оффлайн). В неделю
   2) 1-2 самостоятельных занятий. В неделю
   3) Компьютер достаточный для того чтобы выдерживать нагрузку. Min: Intel i3 (>4 gen), 8-16 Gb памяти, 10 Gb HDD, GPU опционально для ML и анализа информации. Идеально Mac OS или Linux. 80%% можно делать и под Windows. Для остального поможет Docker.
   4) Гражданство РФ и/или постоянное проживание на территории РФ.
   5) Активность на "уроках" и внеурочных занятиях.
7) Disclaimer
   1) Я не профессиональный педагог.
   2) Ограничения по времени.
   3) Нет стабильности во времени.
8) Домашнее задание
   1) Определиться с направлением использования Python как языка программирования.
   2) Сообщить конфигурацию своего "железа".
   3) Ответ на вопрос "зачем я хочу программировать".
9) "Регламент"
   1) Занятия по вторникам и четвергам вечером. (19-20 часов начало).
   2) Занятие идет 50-60 минут.
   3) Домашние задания присылать в "личку" минимум за 4 часа до занятия.
