# Generated by Django 4.1.7 on 2023-03-09 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="modification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 9, 17, 23, 59, 585611)
            ),
        ),
        migrations.CreateModel(
            name="MoneyMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.IntegerField(verbose_name="Сумма в копейках")),
                (
                    "subject",
                    models.CharField(max_length=128, verbose_name="Причина движения"),
                ),
                (
                    "destination_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dstacc",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srcacc",
                        to="accounts.accounts",
                    ),
                ),
            ],
        ),
    ]
