# Generated by Django 4.1.7 on 2023-03-09 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_accounts_modification_date_moneymovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="modification_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 9, 18, 3, 51, 370854)
            ),
        ),
        migrations.AlterField(
            model_name="moneymovement",
            name="source_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="srcacc",
                to="accounts.accounts",
            ),
        ),
    ]
